flush ruleset

table inet firewall {
    chain input {
        type filter hook input priority filter; policy drop;
        iif "lo" accept
        ct state established,related accept
        ct state invalid drop
        ip protocol icmp icmp type echo-request drop
        log prefix "NFT_DROP_IN: " flags all
    }

    chain forward { type filter hook forward priority filter; policy drop; }

    chain output {
        type filter hook output priority filter; policy drop;
        oif "lo" accept
        ct state established,related accept
	udp dport 53 ip daddr { 9.9.9.9, 1.1.1.1 } accept
	tcp dport 53 ip daddr { 9.9.9.9, 1.1.1.1 } accept	
	udp dport { 53, 5353 } ip daddr 127.0.0.1 accept
	tcp dport { 53, 5353 } ip daddr 127.0.0.1 accept
        tcp dport { 80, 443, 853, 3000, 3001, 3002, 3003, 3004, 8445, 8443, 8444, 6379, 9090 } accept
        tcp dport 22 oifname "eth0" accept
        tcp dport { 139, 445 } oifname "eth0" accept
        tcp dport { 8080 } oifname "tun1" accept
        #tcp dport 53 ip daddr != 127.0.0.1 reject
        #udp dport 53 ip daddr != 127.0.0.1 reject
        log prefix "NFT_DROP_OUT: " flags all
    }
}
